version: "3"

services:
    mongodb:
        image: mongo:latest
        environment:
            MONGO_INITDB_DATABASE: "xkom"
            MONGO_INITDB_ROOT_USERNAME: "root"
            MONGO_INITDB_ROOT_PASSWORD: "demo1234"
        volumes:
            - ./mongodb/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
            - ./mongodb/data:/data/db

    api:
        image: cledar/michal-tests:latest
        ports:
            - 7676:5000
        volumes:
            - ./cache:/app/cache
            - ./api:/app
